services:

  nginx:
    build:
      context: ./nginx
    image: hawerroth/nginx:prod
    container_name: nginx
    networks:
      - desafio-network
    ports:
      - "8080:80"

  app:
    build:
      context: ./node
    container_name: app
    networks:
      - desafio-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:9.1.0
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafio-network

networks:
  desafio-network:
    driver: bridge
